name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_api.py
          - tests/test_manual.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests with pytest
        run: |
          pytest ${{ matrix.suite }} --alluredir=allure-results --maxfail=1 --disable-warnings -q
        continue-on-error: true

      - name: Set safe artifact name
        id: sanitize
        run: echo "safe_name=$(echo '${{ matrix.suite }}' | tr '/' '_' | tr '.' '_')" >> $GITHUB_OUTPUT

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ steps.sanitize.outputs.safe_name }}
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          path: combined-results

      - name: Merge Allure results
        run: |
          mkdir -p allure-results
          find combined-results -type d -name 'allure-results-*' -exec cp -r {}/* allure-results/ \;

      - name: Download Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages

      - name: Add link to Allure report in GitHub Actions summary
        run: |
          echo "### ✅ Allure Report is available at:" >> $GITHUB_STEP_SUMMARY
          echo "[🔗 View Allure Report](https://fudu-courses.github.io/automation/)" >> $GITHUB_STEP_SUMMARY
