name: Run Automation Tests

on:
  push:
    branches:
      - main # Trigger this action on push to the main branch
  pull_request:
    branches:
      - main # Trigger this action on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_api.py
          - tests/test_manual.py
        browser:
          - chrome
          - firefox

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install browsers based on matrix configuration (Chrome or Firefox)
      - name: Install browsers
        run: |
          if [ "${{ matrix.browser }}" == "chrome" ]; then
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
          elif [ "${{ matrix.browser }}" == "firefox" ]; then
            sudo apt-get update
            sudo apt-get install -y firefox
          fi

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13" # You can change the Python version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      # Set the browser environment variable
      - name: Set browser environment variable
        run: echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV

      # Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest ${{ matrix.suite }} --maxfail=1 --disable-warnings -q
