name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Create and activate Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save Chrome binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: /usr/bin/google-chrome-stable

      - name: Save Python virtual environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-venv
          path: venv/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_api.py
          - tests/test_manual.py

    steps:
      - name: Download Chrome from artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome
          path: /usr/bin/

      - name: Download Python virtual environment from artifact
        uses: actions/download-artifact@v3
        with:
          name: python-venv
          path: ./

      - name: Set up Python from venv
        run: |
          source venv/bin/activate

      - name: Run tests for ${{ matrix.suite }}
        run: |
          pytest ${{ matrix.suite }} --maxfail=1 --disable-warnings -q
